# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # based on https://github.com/endel/haxelib-publish-github-actions-test/
  check:
    name: Check version
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.check.outputs.version }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: EndBug/version-check@v1
      id: check
      with:
        file-name: haxelib.json
        diff-search: true
        
  publish:
    name: Publish to Haxelib
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.released
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.3
      - run: |
          haxe -version
          haxelib submit . UldisB ${{ secrets.HAXELIB_AUTH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
